#!/usr/bin/env bash

set -ex

cd $(dirname $0)/..

export GOPATH=$(pwd)/Godeps/_workspace:$(pwd)/gopath
mkdir -p $(pwd)/Godeps/_workspace/src/github.com/hibooboo2/
ln -s /ultimateBravery $(pwd)/Godeps/_workspace/src/github.com/hibooboo2/
